definitions:
  domain.RequestRegister:
    properties:
      name:
        maxLength: 100
        type: string
      password:
        maxLength: 100
        minLength: 8
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - name
    - password
    - username
    type: object
  domain.ResponseRegister:
    properties:
      name:
        type: string
      username:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error: {}
    type: object
info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: Register request
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/domain.RequestRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ResponseRegister'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Register
      tags:
      - Auth
swagger: "2.0"
