definitions:
  domain.RequestLogin:
    properties:
      password:
        maxLength: 100
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - password
    - username
    type: object
  domain.RequestRegister:
    properties:
      name:
        maxLength: 100
        type: string
      password:
        maxLength: 100
        minLength: 8
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - name
    - password
    - username
    type: object
  domain.ResponseRefreshToken:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  domain.ResponseRegister:
    properties:
      name:
        type: string
      username:
        type: string
    type: object
  response.ErrorMessageResponse:
    properties:
      attribute: {}
      code:
        type: string
      message:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/response.ErrorMessageResponse'
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register request
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/domain.ResponseRefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.RequestLogin'
        "401":
          description: Username or password is incorect
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Form validation error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register request
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/domain.RequestRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ResponseRegister'
        "409":
          description: Duplicate record
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Form validation error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Register
      tags:
      - Auth
swagger: "2.0"
